Add apt fixes

diff --git a/autobuild-zip b/autobuild-zip
--- a/autobuild-zip
+++ b/autobuild-zip
@@ -21,13 +21,13 @@ if [ $UID -ne 0 ]; then
 fi
 
 
-if [ ! hash simg2img 2>/dev/null ] || [ ! hash img2simg 2>/dev/null ] || [ ! hash brotli 2>/dev/null ] || [ ! hash patch 2>/dev/null ]; then
-	if [ ! hash apt 2>/dev/null ]; then
-		echo ">>ERROR: 'simg2img', 'img2simg', 'brotli' 'patch' 'curl'  are not found! Please install 'patch' 'curl' 'android-tools' and 'brotli'!"
-		exit 1;
-	else
-		apt install android-tools brotli patch -y
-	fi
+if [ ! hash simg2img 2>/dev/null ] || [ ! hash img2simg 2>/dev/null ] || [ ! hash brotli 2>/dev/null ] || [ ! hash patch 2>/dev/null ] && [ ! -e /usr/bin/apt ]; then
+	echo ">>ERROR: 'simg2img', 'img2simg', 'brotli' 'patch' 'curl'  are not found! Please install 'patch' 'curl' 'android-tools' and 'brotli'!"
+	exit 1
+
+elif [ -e /usr/bin/apt ]; then
+	apt install simg2img img2simg brotli curl patch python-is-python3
+
 fi
 
 	
